version: "3.7"
services:
  app:
    build: ./app
    container_name: app
    ports:
      - "3000:3000"
    restart: always
  server:
    build: ./server
    #    image: shortintern2020-C-cryptograph/TeamF/server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/go/src/github.com/shortintern2020-C-cryptograph/TeamF/server/
    environment:
      - DBENV=nexus-db # sql_handler接続先切り替え用
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    container_name: nexus-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data-volume:/var/lib/mysql
      - ./database/init.d:/docker-entrypoint-initdb.d # 起動時にテーブルを作成（data-volumeが無い時だけ動く）

  migration:
    image: flyway/flyway
    depends_on:
      - db
    container_name: nexus-migration
    volumes:
      - ./database/migration/schema:/flyway/sql

volumes:
  data-volume:
